# Generated by Django 5.2.16 on 2026-08-02 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft / Not Started"),
                            ("active", "Active / Running"),
                            ("paused", "Paused"),
                            ("finished", "Finished"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComponentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Type of component e.g. Motor, Body, Fan, Battery",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExamCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Island",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order sequence of the island in the adventure",
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="islands/"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_available", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="LiveExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("duration_seconds", models.PositiveIntegerField(default=300)),
                ("total_points", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "progression_order",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1. Submarine"),
                            (2, "2. Boat"),
                            (3, "3. Car"),
                            (4, "4. Airplane"),
                            (5, "5. Horse Carriage"),
                            (6, "6. Train"),
                            (7, "7. Bicycle"),
                        ],
                        unique=True,
                    ),
                ),
                (
                    "base_travel_time_minutes",
                    models.PositiveIntegerField(
                        default=120, help_text="Base travel time in minutes"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["progression_order"],
            },
        ),
        migrations.CreateModel(
            name="ComponentPowerLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Motor-25, Motor-50, Motor-100", max_length=120
                    ),
                ),
                (
                    "power_value",
                    models.PositiveIntegerField(
                        default=25, help_text="Power level rating e.g. 25, 50, 100"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=12),
                ),
                ("stock", models.PositiveIntegerField(default=999)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="components/"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_levels",
                        to="market.componenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["component_type", "power_value"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("tf", "True / False"),
                            ("short", "Short Answer"),
                        ],
                        default="mcq",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("question_text", models.TextField()),
                ("points", models.PositiveIntegerField(default=10)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "short_answer_correct",
                    models.CharField(
                        blank=True,
                        help_text="Correct answer for Short Answer questions",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.examcategory",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="market.liveexam",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExamChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="market.examquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_submissions",
                        to="accounts.profile",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="market.liveexam",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "exam")},
            },
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_answer", models.TextField(blank=True, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.examchoice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.examquestion",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="market.examsubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamVehicleAssembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_power", models.PositiveIntegerField(default=0)),
                ("power_percentage", models.FloatField(default=0.0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_assemblies",
                        to="accounts.profile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.vehicle"
                    ),
                ),
            ],
            options={
                "ordering": ["vehicle__progression_order"],
                "unique_together": {("profile", "vehicle")},
            },
        ),
        migrations.CreateModel(
            name="TravelHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_power_percentage", models.FloatField(default=100.0)),
                ("base_time_minutes", models.PositiveIntegerField(default=120)),
                ("actual_travel_time_minutes", models.FloatField(default=120.0)),
                ("delay_minutes", models.FloatField(default=0.0)),
                ("departed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="market.island",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_histories",
                        to="accounts.profile",
                    ),
                ),
                (
                    "to_island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="market.island",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.vehicle"
                    ),
                ),
            ],
            options={
                "ordering": ["-departed_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "power_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.componentpowerlevel",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "power_level")},
            },
        ),
        migrations.CreateModel(
            name="TeamComponentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "power_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.componentpowerlevel",
                    ),
                ),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocated_components",
                        to="market.teamvehicleassembly",
                    ),
                ),
            ],
            options={
                "unique_together": {("assembly", "power_level")},
            },
        ),
        migrations.CreateModel(
            name="VehicleComponentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_required", models.PositiveIntegerField(default=1)),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_requirements",
                        to="market.componenttype",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="market.vehicle",
                    ),
                ),
            ],
            options={
                "unique_together": {("vehicle", "component_type")},
            },
        ),
    ]
