# Generated by Django 5.2.16 on 2026-08-02 08:16

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.custom_upload_to,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000.0,
                        max_digits=15,
                        verbose_name="Coins Balance",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                ("teamName", models.TextField(blank=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "members_list",
                    models.TextField(
                        blank=True, help_text="Comma separated team member names"
                    ),
                ),
                (
                    "joindate",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Team Profile",
                "verbose_name_plural": "Team Profiles",
            },
        ),
    ]
