# Generated by Django 5.2.16 on 2026-08-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                verbose_name="Coins Balance",
            ),
        ),
    ]
